name: PlayerStats
main: io.github.sol9109.playerstats.PlayerStats
version: {$VersionNumber}
author: Sol9109
commands:
  resetstats:
    description: Resets the stats of the specified player.
    usage: /resetstats [Player]
  changestats:
    description: Changes the stats of the specified player.
    usage: /changestats [Player] [CombatClass] [Level] [Experience] [Money] [Str] [Dex]
  showstats:
    description: Displays stats of player.
    usage: /showstats